apiVersion: apps/v1
kind: Deployment
metadata:
 name: addressbook
spec:
 replicas: 2
 template:
  metadata:
   labels:
    app: ab
  spec:
   containers:
   - name: addressbook
     image: devopsxprts/ab:latest
     ports:
     - containerPort: 8080
 selector:
  matchLabels:
   app: ab
